### ISSUE TITLE
not a member of 'boost::mpl::vector1

### ISSUE THREAD

**Issue by sherkat69** [tobias-loew/windows_thunks#4]
hi

I'm trying to use windows_thunks to call a winapi in a member function. this is the pseudo of what I'm tryin to do:

```
//constructor
Chook()
		: m_thunk_PvectoredExceptionHandler{ this }
	{
	}
	
	
//member
lunaticpp::thunk<&PvectoredExceptionHandler> m_thunk_PvectoredExceptionHandler;


LONG PvectoredExceptionHandler(_EXCEPTION_POINTERS* ExceptionInfo)
	{
		...
	}
	
	
//usage
VEH_Handle = AddVectoredExceptionHandler(true, (PVECTORED_EXCEPTION_HANDLER)m_thunk_PvectoredExceptionHandler.func());

```

and i get this while compiling:
```
'item2': is not a member of 'boost::mpl::vector1<_EXCEPTION_POINTERS *>'
'type': unknown override specifier
missing type specifier - int assumed. Note: C++ does not support default-int
```

I'm still confused about how to implement this technique on AddVectoredExceptionHandler but the above problem comes first.

**Comment by tobias-loew** [comment]
This was due to a compiler defect with MSVC v141 (VS 2017). It's fixed now.
Just a tip: always mention your build-tool's version and the C++ version used. Makes it easier to find the error.

**Comment by sherkat69** [comment]
I replaced the headers with the updated ones and sorry to report that the problem persists.

windows SDK: 10.0.18362.0
Toolset: v142 (VS 2019)
C++: 17

also tried with v141_xp and got the same error.

**Comment by tobias-loew** [comment]
I made a short example https://godbolt.org/z/bz61zf4PE which uses v142 with C++17 and it compiles without errors. Can you reproduce the error there, or create an example project that reproduces the error and upload it?

**Comment by sherkat69** [comment]
tried several options in godbolt.org and all compiled.
in my machine I tried compiling as x86 and it compiled. I'm having trouble with x64 only.

**Comment by tobias-loew** [comment]
Two questions:

What happens when you replace the two occurrences of

`#if _MSC_VER < 1920`

in line 346 und 361 by

`#if 1`

?

And can you create a little example project that produces the error and upload it?

**Comment by sherkat69** [comment]
i edited the header as you said and the test snippet you gave compiled like butter.
now I'm going to test it with my program to see if it works as intended or not.
if there's anything i can do to help, snapshot, dump or whatever, let me know.

**Comment by tobias-loew** [comment]
That's a good idea. 
You could check the value of `_MSC_VER` of your compiler. It's probably 1916 (or something close by).
Nevertheless, msvc and especially older versions of it sometimes produce errors when the code gets "too complex": all the pieces compile fine, but together it fails. (Like multi-nested `if constexpr` or using code inside a class-template instead of a simple class.)
When your original code compiles with the `#if 1` version, then I'll change `thunks.hpp` to always use that.

**Comment by tobias-loew** [comment]
Any updates?

**Comment by sherkat69** [comment]
sorry for the late reply. 
i tested the thunk with a simple function and it works.


but got another error:
**note:** I don't want you to waste your time updating the header for my lame old VS. if the problem sure gets fixed by updating my VS ill do that.

'item1': is not a member of 'boost::mpl::vector0<boost::mpl::na>'
'type': unknown override specifier
missing type specifier - int assumed. 
while trying to create another thunk:
```
class CShadowHook {

	CShadowHook()
		: m_thunk_PvectoredExceptionHandler{ this }
		, m_thunk_HookMe{ this }  
	{
	}

	void  HookMe() {
		printf("Not hooked\n");
	}
	lunaticpp::thunk<&HookMe> m_thunk_HookMe;  
```


and had a question. how can i implement a copy constructor?
tried this. sorry if looks stupid(cpp newb):
```
CShadowHook(const CShadowHook& other) {
		m_thunk_PvectoredExceptionHandler{ other.this };
		bAsmPh = other.bAsmPh;
		bApplied = other.bApplied;
	}
```

**Comment by tobias-loew** [comment]
I could reproduce your error and fixed it. I also backported until msvc 140 (VS 2015) and C++11. Hopefully your code compiles now.
When copying objects with thunks, you definitely should not copy the this-pointer into the thunk (the this pointer glues the thunk to the object it is a member of). IMHO the best way to prevent this is by initializing thunks not in the constructor but directly at the member definition, then you do not have to take care about thunks in constructors:

```
class CShadowHook {

	CShadowHook()
	{
        }

        CShadowHook(const CShadowHook& other) {
		bAsmPh = other.bAsmPh;
		bApplied = other.bApplied;
	}

	void  HookMe() {
		printf("Not hooked\n");
	}
	lunaticpp::thunk<&HookMe> m_thunk_HookMe{this};  

       bool bAsmPh;
       bool bApplied;
};
```

**Comment by sherkat69** [comment]
many thanks for the fix and advice.

**Comment by tobias-loew** [comment]
I'll close the issue for now. Feel free to reopen in case another error pops up.
